import { writeFileSync, chmodSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

import { colors, designTokens } from "../src/styles/design-tokens.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

function toKebabCase(str: string): string {
  return str.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function normalizeColorValue(value: string): string {
  return value.toUpperCase();
}

function lowercaseHex(value: string): string {
  return value.replace(
    /#([0-9A-Fa-f]+)/g,
    (_match, hex) => `#${hex.toLowerCase()}`
  );
}

function findColorKey(
  value: string,
  colorsObj: Record<string, string>,
  tokenKey?: string
): string | null {
  const normalizedValue = normalizeColorValue(value);

  if (
    tokenKey === "text-inverted" &&
    colorsObj["base-dark-1"] &&
    normalizeColorValue(colorsObj["base-dark-1"]) === normalizedValue
  ) {
    return "base-dark-1";
  }

  const entries = Object.entries(colorsObj);
  for (let i = entries.length - 1; i >= 0; i--) {
    const [key, colorValue] = entries[i];
    if (normalizeColorValue(colorValue) === normalizedValue) {
      return key;
    }
  }
  return null;
}

function generateCSSVariable(
  key: string,
  value: string,
  colorsObj: Record<string, string>
): string {
  const kebabKey = toKebabCase(key);
  const normalizedValue = normalizeColorValue(value);

  let colorKey: string | null = null;

  if (
    colorsObj[key] &&
    normalizeColorValue(colorsObj[key]) === normalizedValue
  ) {
    colorKey = key;
  } else {
    colorKey = findColorKey(value, colorsObj, key);
  }

  const cssValue = colorKey
    ? `var(--mt-color-${toKebabCase(colorKey)})`
    : lowercaseHex(value);
  return `  --mt-color-${kebabKey}: ${cssValue};`;
}

function generateCSS(): string {
  let css = "/* DO NOT EDIT THIS FILE MANUALLY */\n";
  css += "/* This file is auto-generated from design-tokens.ts */\n";
  css += "/* Run 'pnpm generate:theme' to regenerate */\n";
  css += "/* Changes will be automatically regenerated on git commit */\n\n";
  css += ":root {\n";

  for (const [key, value] of Object.entries(colors)) {
    const kebabKey = toKebabCase(key);
    css += `  --mt-color-${kebabKey}: ${lowercaseHex(value)};\n`;
  }

  css += `  --mt-shadow-xs-light: 0px 1px 2px 0px var(--mt-color-gray-13-shadow);\n`;
  css += `  --mt-shadow-xs-dark: 0px 1px 2px 0px rgb(255 255 255 / 0%);\n`;
  css += `  --mt-shadow-tooltip-sm-light: 0px 10px 16px -3px var(--mt-color-gray-13-shadow),\n`;
  css += `    0px 3px 10px -2px var(--mt-color-gray-13-shadow-2);\n`;
  css += `  --mt-shadow-tooltip-sm-dark: 0px 10px 16px -3px rgb(20 21 26 / 5%),\n`;
  css += `    0px 3px 10px -2px rgb(20 21 26 / 2%);\n`;
  css += `  --mt-focus-light-light: 0px 0px 0px 2px var(--mt-color-gray-2a);\n`;
  css += `  --mt-focus-light-dark: 0px 0px 0px 2px var(--mt-color-white-2);\n`;
  css += `  --mt-focus-accent-light: 0px 0px 0px 2px var(--mt-color-green-8);\n`;
  css += `  --mt-focus-accent-dark: 0px 0px 0px 2px var(--mt-color-green-8);\n`;
  css += `  --mt-focus-light-destructive-light: 0px 0px 0px 2px\n`;
  css += `    var(--mt-color-red-1-focus);\n`;
  css += `  --mt-focus-light-destructive-dark: 0px 0px 0px 2px var(--mt-color-red-1-focus);\n`;

  const lightTokens = designTokens.light;
  const skipKeys = new Set([
    "shadow-xs",
    "shadow-tooltip-sm",
    "focus-light",
    "focus-accent",
    "focus-light-destructive",
    "red-1-focus",
  ]);
  for (const [key, value] of Object.entries(lightTokens)) {
    if (skipKeys.has(key)) continue;
    css += generateCSSVariable(key, value, colors) + "\n";
  }

  css += `  --mt-color-shadow-xs: var(--mt-shadow-xs-light);\n`;
  css += `  --mt-color-shadow-tooltip-sm: var(--mt-shadow-tooltip-sm-light);\n`;
  css += `  --mt-color-focus-light: var(--mt-focus-light-light);\n`;
  css += `  --mt-color-focus-accent: var(--mt-focus-accent-light);\n`;
  css += `  --mt-color-focus-light-destructive: var(--mt-focus-light-destructive-light);\n`;
  css += "}\n\n";

  css += "@media (prefers-color-scheme: dark) {\n";
  css += "  :root {\n";
  const darkTokens = designTokens.dark;
  const skipKeysDark = new Set([
    "shadow-xs",
    "shadow-tooltip-sm",
    "focus-light",
    "focus-accent",
    "focus-light-destructive",
  ]);

  css += `  --mt-color-red-1-focus: var(--mt-color-red-1-focus);\n`;

  for (const [key, value] of Object.entries(darkTokens)) {
    if (key === "red-1-focus" || skipKeysDark.has(key)) continue;
    css += generateCSSVariable(key, value, colors) + "\n";
  }

  css += `  --mt-color-shadow-xs: var(--mt-shadow-xs-dark);\n`;
  css += `  --mt-color-shadow-tooltip-sm: var(--mt-shadow-tooltip-sm-dark);\n`;
  css += `  --mt-color-focus-light: var(--mt-focus-light-dark);\n`;
  css += `  --mt-color-focus-accent: var(--mt-focus-accent-dark);\n`;
  css += `  --mt-color-focus-light-destructive: var(--mt-focus-light-destructive-dark);\n`;
  css += "\n";
  css += "    color-scheme: dark;\n";
  css += "  }\n";
  css += "}\n\n";

  return css;
}

const outputPath = join(__dirname, "../src/styles/theme.css");
const css = generateCSS();

try {
  chmodSync(outputPath, 0o644);
} catch (error) {}

writeFileSync(outputPath, css, "utf-8");

chmodSync(outputPath, 0o444);

console.log(`✅ Successfully generated theme.css (readonly)`);
