const _classes = {
    Accordion: 'accordion',
    AccordionGroup: 'accordion-group',
    Callout: 'callout',
    Card: 'card',
    CardGroup: 'card-group',
    CodeBlock: 'code-block',
    CodeBlockIcon: 'code-block-icon',
    CodeGroup: 'code-group',
    Expandable: 'expandable',
    Field: 'field',
    Frame: 'frame',
    Icon: 'icon',
    Mermaid: 'mermaid',
    Step: 'step',
    Steps: 'steps',
    Tab: 'tab',
    Tabs: 'tabs',
    TabIcon: 'tab-icon',
    Update: 'update',
    Tooltip: 'tooltip',
    Panel: 'panel',
    APISection: 'api-section',
    APISectionHeading: 'api-section-heading',
    APISectionHeadingTitle: 'api-section-heading-title',
    APISectionHeadingSubtitle: 'api-section-heading-subtitle',
    OptionDropdown: 'option-dropdown',
    TryitButton: 'tryit-button',
    MethodPill: 'method-pill',
    MethodNavPill: 'method-nav-pill',
    NavTagPill: 'nav-tag-pill',
    NavTagPillText: 'nav-tag-pill-text',

    Anchors: 'nav-anchors',
    Anchor: 'nav-anchor',
    TabsBar: 'nav-tabs',
    TabsBarItem: 'nav-tabs-item',
    MobileNavTabsBarItem: 'mobile-nav-tabs-item',
    TableOfContents: 'toc',
    TableOfContentsItem: 'toc-item',
    Footer: 'footer',
    AdvancedFooter: 'advanced-footer',
    SidebarGroupIcon: 'sidebar-group-icon',
    SidebarGroupHeader: 'sidebar-group-header',
    SidebarTitle: 'sidebar-title',
    SidebarGroup: 'sidebar-group',
    SidebarNavGroupDivider: 'sidebar-nav-group-divider',
    NavBarLink: 'navbar-link',
    TopbarRightContainer: 'topbar-right-container',
    Logo: 'nav-logo',
    PaginationPrev: 'pagination-prev',
    PaginationNext: 'pagination-next',
    PaginationTitle: 'pagination-title',
    FeedbackToolbar: 'feedback-toolbar',
    Eyebrow: 'eyebrow',
    BreadcrumbList: 'breadcrumb-list',
    BreadcrumbItem: 'breadcrumb-item',
    Content: 'mdx-content',
    DropdownTrigger: 'nav-dropdown-trigger',
    DropdownContent: 'nav-dropdown-content',
    DropdownItem: 'nav-dropdown-item',
    DropdownItemTextContainer: 'nav-dropdown-item-text-container',
    DropdownItemTitle: 'nav-dropdown-item-title',
    DropdownItemDescription: 'nav-dropdown-item-description',
    DropdownItemIcon: 'nav-dropdown-item-icon',
    ProductsSelectorTrigger: 'nav-dropdown-products-selector-trigger',
    ProductsSelectorContent: 'nav-dropdown-products-selector-content',
    ProductsSelectorItem: 'nav-dropdown-products-selector-item',
    ProductsSelectorItemTitle: 'nav-dropdown-products-selector-item-title',
    ProductsSelectorItemDescription: 'nav-dropdown-products-selector-item-description',
    ProductsSelectorItemIcon: 'nav-dropdown-products-selector-item-icon',

    Link: 'link',

    AlmondLayout: 'almond-layout',
    AlmondNavBottomSection: 'almond-nav-bottom-section',
    AlmondNavBottomSectionDivider: 'almond-nav-bottom-section-divider',

    ChatAssistantSheet: 'chat-assistant-sheet',
    ChatAssistantSheetHeader: 'chat-assistant-sheet-header',
    ChatAssistantSheetContent: 'chat-assistant-sheet-content',
    ChatAssistantInput: 'chat-assistant-input',
    ChatAssistantFloatingInput: 'chat-assistant-floating-input',
    ChatAssistantSendButton: 'chat-assistant-send-button',
    ChatAssistantDisclaimerText: 'chat-assistant-disclaimer-text',
    ChatAssistantPayloadItem: 'chat-assistant-payload-item',
    StarterQuestionText: 'starter-question-text',

    LoginLink: 'login-link',
    LogoutLink: 'logout-link',

    ContextualFeedbackContainer: 'contextual-feedback-container',
    ContextualFeedbackForm: 'contextual-feedback-form',
    ContextualFeedbackFormTitle: 'contextual-feedback-form-title',
    ContextualFeedbackFormInput: 'contextual-feedback-input',
    ContextualFeedbackFormButton: 'contextual-feedback-button',
    ContextualFeedbackFormSubmitButton: 'contextual-feedback-form-submit-button',

    CodeSnippetFeedbackPopoverContent: 'code-snippet-feedback-popover-content',
    CodeSnippetFeedbackForm: 'code-snippet-feedback-form',
    CodeSnippetFeedbackButton: 'code-snippet-feedback-button',
    CodeSnippetFeedbackTextArea: 'code-snippet-feedback-textarea',
    CodeSnippetFeedbackFormTitle: 'code-snippet-feedback-form-title',
    CodeSnippetFeedbackFormDescription: 'code-snippet-feedback-form-description',
    CodeSnippetFeedbackFormSubmitButton: 'code-snippet-feedback-form-submit-button',

    NotFoundContainer: 'not-found-container',
    NotFoundStatusCode: 'not-found-status-code',
    NotFoundTitle: 'not-found-title',
    NotFoundDescription: 'not-found-description',
    NotFoundLogo: 'not-found-logo',
    NotFoundLogoContainer: 'not-found-logo-container',
    NotFoundMessage: 'not-found-message',
    NotFoundGoBackButton: 'not-found-go-back-button',
    NotFoundGoBackArrow: 'not-found-go-back-arrow',
    NotFoundGoBackText: 'not-found-go-back-text',
    NotFoundRecommendedPagesList: 'not-found-recommended-pages-list',
    NotFoundRecommendedPageLink: 'not-found-recommended-page-link',

    MultiViewItem: 'multi-view-item',
    MultiViewDropdown: 'multi-view-dropdown',
    MultiViewDropdownTrigger: 'multi-view-dropdown-trigger',
    MultiViewDropdownContent: 'multi-view-dropdown-content',
    MultiViewDropdownItem: 'multi-view-dropdown-item',

    Color: 'color',
    ColorRow: 'color-row',
    ColorItem: 'color-item',

    Tile: 'tile',

    Tree: 'tree',
    TreeFolder: 'tree-folder',
    TreeFile: 'tree-file',

    ResponseExample: 'response-example',
} as const;

export const Classes = Object.fromEntries(
    Object.entries(_classes).map(([key, value]) => [key, `${value}`])
) as { readonly [K in keyof typeof _classes]: `${(typeof _classes)[K]}` };
