const colors = {
  "base-white": "#ffffff",
  "base-dark-1": "#0B0C0E",
  "base-transparent": "#FFFFFF02",
  "icon-gray-2": "#757575",
  "icon-gray-3": "#525252",
  "gray-13-shadow": "#14151A0D",
  "gray-13-shadow-2": "#14151A05",
  "red-1-focus": "#FFB2B299",

  "gray-1": "#F9F9F9",
  "gray-2": "#F5F5F5",
  "gray-3": "#E9E9EA",
  "gray-4": "#D7D7D7",
  "gray-5": "#BBBBBC",
  "gray-6": "#9B9B9C",
  "gray-7": "#78787A",
  "gray-8": "#585859",
  "gray-9": "#3C3C3D",
  "gray-10": "#262727",
  "gray-11": "#191A1B",
  "gray-12": "#0F1011",
  "gray-13": "#0B0C0E",
  "gray-1a": "#0B0C0E0A",
  "gray-2a": "#0B0C0E14",
  "gray-5a": "#0B0C0E40",
  "gray-5a-solid": "#C2C2C2",
  "gray-7a": "#0B0C0E66",
  "gray-9a": "#0B0C0E80",
  "gray-9a-solid": "#6D6D6E",

  "white-1": "#FFFFFF14",
  "white-2": "#FFFFFF24",
  "white-3": "#FFFFFF2E",
  "white-4": "#FFFFFF3D",
  "white-5": "#FFFFFF52",
  "white-5-solid": "#B2B2B4",
  "white-6": "#FFFFFF66",
  "white-7": "#FFFFFF75",
  "white-9": "#FFFFFF99",
  "white-9-solid": "#a0a1a3",
  "white-13": "#FFFFFFF2",

  "blue-1": "#F0F4FE",
  "blue-2": "#E3EAFD",
  "blue-6": "#7196F4",
  "blue-8": "#4778F5",
  "blue-9": "#1D54E2",
  "blue-12": "#07296A",
  "blue-11": "#133A9A",
  "blue-3a": "#3368F033",
  "blue-5a": "#3368F04D",
  "blue-7a": "#3368F080",

  "green-1": "#EDFDF4",
  "green-2": "#D1FAE4",
  "green-3": "#C3F8DC",
  "green-4": "#9AF4C3",
  "green-6": "#6AE1A1",
  "green-7": "#40D986",
  "green-8": "#26BD6C",
  "green-9": "#21A65E",
  "green-10": "#1D9052",
  "green-11": "#166E3F",
  "green-12": "#0F4C2C",
  "green-13": "#072213",
  "green-1a": "#26BD6C1A",
  "green-3a": "#26BD6C33",
  "green-4a": "#26BD6C40",
  "green-5a": "#26BD6C4D",
  "green-7a": "#26BD6C80",
  "green-11a": "#26BD6CE6",

  "orange-1": "#FEF4EC",
  "orange-2": "#FDEAD8",
  "orange-4": "#FAD0A9",
  "orange-6": "#F8B577",
  "orange-8": "#F48E2F",
  "orange-9": "#E9760C",
  "orange-11": "#AE590A",
  "orange-12": "#613105",
  "orange-13": "#301903",
  "orange-3a": "#F48E2F33",
  "orange-4a": "#F48E2F40",
  "orange-5a": "#F48E2F4D",
  "orange-7a": "#F48E2F80",

  "red-1": "#FDF2F1",
  "red-2": "#FCE5E4",
  "red-4": "#F7C3C0",
  "red-5": "#F5B2AD",
  "red-6": "#F08B85",
  "red-8": "#E6483D",
  "red-9": "#D9281C",
  "red-11": "#9A1C13",
  "red-12": "#64120D",
  "red-13": "#360A07",
  "red-1a": "#E6483D1A",
  "red-2a": "#E6483D26",
  "red-3a": "#E6483D33",
  "red-4a": "#E6483D40",
  "red-5a": "#E6483D4D",
  "red-6a": "#E6483D66",
  "red-7a": "#E6483D80",
  "red-9a": "#E6483DB3",

  "purple-1": "#F7F1FD",
  "purple-2": "#ECDFFB",
  "purple-6": "#B78AF0",
  "purple-8": "#924FE8",
  "purple-11": "#5314A3",
  "purple-12": "#3A0F71",
  "purple-13": "#1C0736",
  "purple-3a": "#873DE633",
  "purple-5a": "#873DE64D",
  "purple-7a": "#873DE680",
};

const shadows = {
  "xs-light": `0px 1px 2px 0px ${colors["gray-13-shadow"]}`,
  "xs-dark": `0px 1px 2px 0px rgba(255, 255, 255, 0)`,
  "tooltip-sm-light": `0px 10px 16px -3px ${colors["gray-13-shadow"]}, 0px 3px 10px -2px ${colors["gray-13-shadow-2"]}`,
  "tooltip-sm-dark": `0px 10px 16px -3px rgba(20, 21, 26, 0.05), 0px 3px 10px -2px rgba(20, 21, 26, 0.02)`,
};

const focus = {
  "light-light": `0px 0px 0px 2px ${colors["gray-2a"]}`,
  "light-dark": `0px 0px 0px 2px ${colors["white-2"]}`,
  "accent-light": `0px 0px 0px 2px ${colors["green-8"]}`,
  "accent-dark": `0px 0px 0px 2px ${colors["green-8"]}`,
  "light-destructive-light": `0px 0px 0px 2px ${colors["red-1-focus"]}`,
  "light-destructive-dark": `0px 0px 0px 2px ${colors["red-1-focus"]}`,
};

export const designTokens = {
  light: {
    "red-1-focus": colors["red-1-focus"],

    "brand-7": colors["green-7"],
    "brand-1a": colors["green-1a"],
    "brand-10": colors["green-10"],
    "brand-4a": colors["green-4a"],
    "brand-11a": colors["green-11a"],

    "surface-neutral": colors["gray-1"],
    "surface-neutral-subtle": colors["gray-2"],
    "surface-warning": colors["orange-1"],
    "surface-info-accent": colors["blue-8"],

    "primary-hover": colors["gray-12"],
    "primary-disabled": colors["gray-2"],

    "button-secondary": colors["base-white"],
    "button-secondary-hover": colors["gray-1"],
    "button-tertiary": colors["gray-1a"],
    "tertiary-hover": colors["gray-2a"],

    ghost: colors["base-transparent"],
    "ghost-hover": colors["gray-1a"],

    "destructive-hover": colors["red-9"],
    "destructive-disabled": colors["red-2"],
    "destructive-secondary-hover": colors["red-1"],
    "button-destructive-tertiary": colors["red-1a"],
    "destructive-tertiary-hover": colors["red-2a"],
    "destructive-ghost-hover": colors["red-1a"],

    "badge-gray": colors["gray-2"],
    "badge-gray-accent": colors["gray-9"],
    "badge-blue": colors["blue-2"],
    "badge-blue-disabled": colors["blue-1"],
    "badge-green": colors["green-2"],
    "badge-green-disabled": colors["green-1"],
    "badge-orange": colors["orange-2"],
    "badge-orange-disabled": colors["orange-1"],
    "badge-red": colors["red-2"],
    "badge-red-disabled": colors["red-1"],
    "badge-purple": colors["purple-2"],
    "badge-purple-disabled": colors["purple-1"],
    "badge-purple-accent": colors["purple-8"],
    "badge-white-disabled": colors["base-white"],
    "badge-surface": colors["base-white"],

    "accent-blue-accent": colors["blue-8"],
    "accent-blue-subtle": colors["blue-2"],
    "accent-gray-accent": colors["gray-8"],
    "accent-green": colors["green-1"],
    "accent-green-accent": colors["green-8"],
    "accent-green-subtle": colors["green-2"],
    "accent-orange-subtle": colors["orange-2"],
    "accent-orange-accent": colors["orange-8"],
    "accent-red": colors["red-1"],
    "accent-red-subtle": colors["red-2"],
    "accent-red-accent": colors["red-8"],
    "accent-purple": colors["purple-1"],
    "accent-purple-subtle": colors["purple-2"],
    "accent-purple-accent": colors["purple-8"],

    "checkbox-disabled": colors["gray-3"],
    "toggle-default": colors["gray-5"],
    "toggle-hover": colors["gray-6"],
    "toggle-active-hover": colors["green-9"],
    "toggle-active-disabled": colors["green-3"],
    "toggle-handle-disabled": colors["gray-4"],

    "border-action-normal": colors["gray-3"],
    "border-action-hover": colors["gray-4"],
    "border-action-focus": colors["gray-13"],

    "border-action-focus-destructive-light": colors["red-6"],
    "border-action-destructive": colors["red-4"],
    "border-action-destructive-hover": colors["red-5"],

    "border-base-warning": colors["orange-4"],
    "border-base-destructive": colors["red-4"],
    "border-base-alpha": colors["gray-2a"],
    "border-base-alpha-white": colors["white-3"],

    "text-primary": colors["gray-13"],
    "text-secondary": colors["gray-9a"],
    "text-secondary-solid": colors["gray-9a-solid"],
    "text-tertiary": colors["gray-7a"],
    "text-quaternary": colors["gray-5a"],
    "text-quaternary-solid": colors["gray-5a-solid"],
    "text-inverted": colors["base-white"],
    "text-static-dark": colors["gray-13"],
    "text-static-dark-secondary": colors["gray-9a"],
    "text-destructive": colors["red-8"],
    "text-destructive-secondary": colors["red-9a"],
    "text-destructive-tertiary": colors["red-5a"],
    "text-success": colors["green-8"],
    "text-warning": colors["orange-8"],
    "text-accent-blue-inverted": colors["blue-11"],
    "text-accent-blue-secondary": colors["blue-7a"],
    "text-accent-blue-tertiary": colors["blue-5a"],
    "text-accent-green": colors["green-11"],
    "text-accent-green-inverted": colors["green-11"],
    "text-accent-green-secondary": colors["green-7a"],
    "text-accent-orange-inverted": colors["orange-11"],
    "text-accent-orange-secondary": colors["orange-7a"],
    "text-accent-red-inverted": colors["red-11"],
    "text-accent-red-secondary": colors["red-7a"],
    "text-accent-purple-inverted": colors["purple-11"],
    "text-accent-purple-secondary": colors["purple-7a"],
    "icon-tertiary": colors["gray-6"],
    "icon-quaternary": colors["gray-4"],

    "shadow-xs": shadows["xs-light"],
    "shadow-tooltip-sm": shadows["tooltip-sm-light"],
    "focus-light": focus["light-light"],
    "focus-accent": focus["accent-light"],
    "focus-light-destructive": focus["light-destructive-light"],
  },
  dark: {
    "red-1-focus": colors["red-1-focus"],
    "brand-1a": colors["green-1"],
    "brand-7": colors["green-7"],
    "brand-10": colors["green-4"],
    "brand-4a": colors["green-4"],
    "brand-11a": colors["green-11"],
    "surface-inverted": colors["base-white"],
    "surface-neutral": colors["gray-13"],
    "surface-neutral-subtle": colors["gray-12"],
    "surface-warning": colors["orange-13"],
    "surface-info-accent": colors["blue-8"],
    "primary-hover": colors["gray-2"],
    "primary-disabled": colors["white-2"],
    "button-secondary": colors["gray-13"],
    "button-secondary-hover": colors["gray-12"],
    "button-tertiary": colors["white-1"],
    "tertiary-hover": colors["white-2"],
    ghost: colors["base-transparent"],
    "ghost-hover": colors["white-2"],
    "destructive-hover": colors["red-9"],
    "destructive-disabled": colors["red-2a"],
    "destructive-secondary-hover": colors["gray-13"],
    "button-destructive-tertiary": colors["white-1"],
    "destructive-tertiary-hover": colors["white-2"],
    "destructive-ghost-hover": colors["white-1"],
    "badge-gray": colors["white-3"],
    "badge-gray-accent": colors["gray-7"],
    "badge-blue": colors["blue-5a"],
    "badge-blue-disabled": colors["blue-3a"],
    "badge-green": colors["green-5a"],
    "badge-green-disabled": colors["green-3a"],
    "badge-orange": colors["orange-4a"],
    "badge-orange-disabled": colors["orange-3a"],
    "badge-red": colors["red-5a"],
    "badge-red-disabled": colors["red-3a"],
    "badge-purple": colors["purple-5a"],
    "badge-purple-disabled": colors["purple-3a"],
    "badge-purple-accent": colors["purple-8"],
    "badge-white-disabled": colors["white-6"],
    "badge-surface": colors["gray-12"],
    "accent-blue-accent": colors["blue-9"],
    "accent-blue-subtle": colors["blue-12"],
    "accent-gray-accent": colors["gray-9"],
    "accent-green": colors["green-13"],
    "accent-green-accent": colors["green-9"],
    "accent-green-subtle": colors["green-12"],
    "accent-orange-subtle": colors["orange-12"],
    "accent-orange-accent": colors["orange-9"],
    "accent-red": colors["red-13"],
    "accent-red-subtle": colors["red-12"],
    "accent-red-accent": colors["red-9"],
    "accent-purple": colors["purple-13"],
    "accent-purple-subtle": colors["purple-12"],
    "accent-purple-accent": colors["purple-8"],
    "checkbox-disabled": colors["gray-11"],
    "toggle-default": colors["gray-9"],
    "toggle-hover": colors["gray-8"],
    "toggle-active-hover": colors["green-9"],
    "toggle-active-disabled": colors["green-11"],
    "toggle-handle-disabled": colors["gray-10"],
    "border-action-normal": colors["white-3"],
    "border-action-hover": colors["white-4"],
    "border-action-focus": colors["white-13"],
    "border-action-focus-destructive-light": colors["red-6"],
    "border-action-destructive": colors["red-4a"],
    "border-action-destructive-hover": colors["red-5a"],
    "border-action-success": colors["green-4a"],
    "border-base-warning": colors["orange-4a"],
    "border-base-destructive": colors["red-4a"],
    "border-base-alpha": colors["gray-2a"],
    "border-base-alpha-white": colors["white-3"],
    "text-primary": colors["base-white"],
    "text-secondary": colors["gray-4"],
    "text-secondary-solid": colors["gray-5a-solid"],
    "text-tertiary": colors["white-7"],
    "text-quaternary": colors["white-5"],
    "text-quaternary-solid": colors["white-5-solid"],
    "text-inverted": colors["base-dark-1"],
    "text-static-dark": colors["gray-13"],
    "text-static-dark-secondary": colors["gray-9a"],
    "text-destructive": colors["red-8"],
    "text-destructive-secondary": colors["red-9a"],
    "text-destructive-tertiary": colors["red-6a"],
    "text-success": colors["green-8"],
    "text-warning": colors["orange-8"],
    "text-accent-blue-inverted": colors["blue-6"],
    "text-accent-blue-secondary": colors["blue-5a"],
    "text-accent-blue-tertiary": colors["blue-3a"],
    "text-accent-green": colors["green-9"],
    "text-accent-green-inverted": colors["green-6"],
    "text-accent-green-secondary": colors["green-5a"],
    "text-accent-orange-inverted": colors["orange-6"],
    "text-accent-orange-secondary": colors["orange-5a"],
    "text-accent-red-inverted": colors["red-6"],
    "text-accent-red-secondary": colors["red-5a"],
    "text-accent-purple-inverted": colors["purple-6"],
    "text-accent-purple-secondary": colors["purple-5a"],
    "icon-tertiary": colors["icon-gray-2"],
    "icon-quaternary": colors["icon-gray-3"],
    "shadow-xs": shadows["xs-dark"],
    "shadow-tooltip-sm": shadows["tooltip-sm-dark"],
    "focus-light": focus["light-dark"],
    "focus-accent": focus["accent-dark"],
    "focus-light-destructive": focus["light-destructive-dark"],
  },
};

export { colors, shadows, focus };
