const MINTLIFY_ICONS_CDN_URL = "https://d3gk2c5xim1je2.cloudfront.net";
const MAX_DEFAULT_VALUE_LENGTH = 50;
const MAX_PREVIEW_BYTES = 50_000; // 0.05 mb / 50 kb
const CHILD_TAB_IDS_ATTRIBUTE = "data-child-tab-ids";
const CHILD_HEADING_IDS_ATTRIBUTE = "data-child-heading-ids";

export {
  CHILD_HEADING_IDS_ATTRIBUTE,
  CHILD_TAB_IDS_ATTRIBUTE,
  MINTLIFY_ICONS_CDN_URL,
  MAX_DEFAULT_VALUE_LENGTH,
  MAX_PREVIEW_BYTES,
};
